# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0e0c93dc6d6a27c666ed703d227c07b1e630156101ab3d0c38da0667cb7c4113be19cf59e4311a9fe93de227e354f051543ea56232ec49148a83cc7d2d861f3

test:
  secret_key_base: 1e327d1ec36a6544bc63a6a6a41d3b3c65df4796959f67845a7c3d4d3f14f2cb8ed6bccd99d39679a2402d7655851ac77b969cca206d8c7ff2cdc6af88596b71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
